export enum watchActionTypes {
    WATCH_NOW = "WATCH_NOW",
    WATCH_MOVIE_SUCCESS = "WATCH_MOVIE_SUCCESS",
    WATCH_MOVIE_FAILURE = "WATCH_MOVIE_FAILURE",
    CLEAR_WATCH_LIST = "CLEAR_WATCH_LIST",
  }
  