export enum trailerActionTypes {
    GET_TRAILER = "GET_TRAILER",
    GET_TRAILER_SUCCESS = "GET_TRAILER_SUCCESS",
    GET_TRAILER_FAILURE = "GET_TRAILER_FAILURE",
    CLEAR_TRAILERS = "CLEAR_TRAILERS",
  }
  